package com.projeto.cortex.intelligence.stavia.intent;

public enum StaviaIntent {
    CONSULTAR_OBRA,
    CONSULTAR_ESTADO_ATUAL,
    CONSULTAR_HISTORICO,
    CONSULTAR_RDO,
    CONSULTAR_PROGRAMACAO,
    CONSULTAR_EQUIPE,
    CONSULTAR_ATIVO,
    CONSULTAR_OCORRENCIA,
    CONSULTAR_PDOC,
    CONSULTAR_RECEITA,
    CONSULTAR_MARGEM,
    CONSULTAR_PREVISAO_FINANCEIRA,
    CONSULTAR_PRODUCAO,
    CONSULTAR_RECEITA_EM_RISCO,
    CONSULTAR_ALOCACAO_COLABORADOR,
    CONSULTAR_FREQUENCIA,
    CONSULTAR_BANCO_HORAS,
    RESUMIR_OBRA,
    DESCONHECIDA
}
