spring:
  config:
    activate:
      on-profile: postgresql-common
  datasource:
    url: ${CORTEX_POSTGRES_URL}
    username: ${CORTEX_POSTGRES_USER:joaolucas}
    password: ${CORTEX_POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
  flyway:
    locations: classpath:db/migration-postgresql

cortex:
  postgresql:
    required-schema-version: 64
    release-marker:
      required: ${CORTEX_POSTGRES_RELEASE_MARKER_REQUIRED:false}
