-- Post-V49 RDO context hardening. V48 is immutable because it may already be
-- recorded in production Flyway history.

ALTER TABLE rdo
    ADD COLUMN creation_owner_id varchar(36),
    ADD COLUMN creation_payload_hash varchar(64);

ALTER TABLE rdo
    ADD CONSTRAINT fk_rdo_creation_owner
        FOREIGN KEY (creation_owner_id)
        REFERENCES colaborador(id) ON DELETE RESTRICT,
    ADD CONSTRAINT chk_rdo_creation_payload_hash
        CHECK (
            creation_payload_hash IS NULL
            OR creation_payload_hash ~ '^[0-9a-f]{64}$'
        );

DROP INDEX uq_rdo_client_mutation;

CREATE UNIQUE INDEX uq_rdo_owner_client_mutation
    ON rdo (creation_owner_id, client_mutation_id)
    WHERE creation_owner_id IS NOT NULL
      AND client_mutation_id IS NOT NULL;

CREATE INDEX idx_rdo_creation_owner ON rdo (creation_owner_id);

-- Asset/worksite eligibility is explicit. Historical RDO links only seed the
-- authoritative relation during upgrade; runtime reads never infer scope from
-- arbitrary prior rows.
CREATE TABLE asset_obra_eligibilidade (
    asset_id varchar(36) NOT NULL REFERENCES asset(id) ON DELETE RESTRICT,
    obra_id varchar(36) NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    status varchar(16) NOT NULL DEFAULT 'ATIVO',
    origem varchar(40) NOT NULL,
    criado_em timestamp with time zone NOT NULL DEFAULT now(),
    atualizado_em timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (asset_id, obra_id),
    CONSTRAINT chk_asset_obra_eligibilidade_status
        CHECK (status IN ('ATIVO', 'INATIVO'))
);

INSERT INTO asset_obra_eligibilidade (asset_id, obra_id, status, origem)
SELECT DISTINCT item.asset_id, rdo.obra_id, 'ATIVO', 'HISTORICO_RDO_V50'
FROM rdo_equipamento item
JOIN rdo ON rdo.id = item.rdo_id
WHERE item.asset_id IS NOT NULL
ON CONFLICT (asset_id, obra_id) DO NOTHING;

ALTER TABLE rdo_equipamento ADD COLUMN obra_id varchar(36);

UPDATE rdo_equipamento item
SET obra_id = rdo.obra_id
FROM rdo
WHERE rdo.id = item.rdo_id;

ALTER TABLE rdo_equipamento
    ALTER COLUMN obra_id SET NOT NULL,
    ADD CONSTRAINT fk_rdo_equipamento_same_obra
        FOREIGN KEY (rdo_id, obra_id)
        REFERENCES rdo(id, obra_id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_rdo_equipamento_asset_obra
        FOREIGN KEY (asset_id, obra_id)
        REFERENCES asset_obra_eligibilidade(asset_id, obra_id)
        ON DELETE RESTRICT;

CREATE INDEX idx_asset_obra_eligibilidade_obra
    ON asset_obra_eligibilidade (obra_id, status, asset_id);

CREATE OR REPLACE FUNCTION enforce_rdo_equipamento_obra_scope()
RETURNS trigger AS $$
DECLARE
    expected_obra_id varchar(36);
BEGIN
    SELECT obra_id INTO expected_obra_id FROM rdo WHERE id = NEW.rdo_id;
    IF expected_obra_id IS NULL THEN
        RAISE EXCEPTION 'RDO inexistente para equipamento';
    END IF;
    IF NEW.obra_id IS NOT NULL AND NEW.obra_id <> expected_obra_id THEN
        RAISE EXCEPTION 'obra_id do equipamento diverge do RDO';
    END IF;
    NEW.obra_id := expected_obra_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_rdo_equipamento_obra_scope
BEFORE INSERT OR UPDATE OF rdo_id, obra_id ON rdo_equipamento
FOR EACH ROW EXECUTE FUNCTION enforce_rdo_equipamento_obra_scope();

CREATE TABLE rdo_creation_context_snapshot (
    receipt_version bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id varchar(36) NOT NULL UNIQUE,
    obra_id varchar(36) NOT NULL REFERENCES obra(id) ON DELETE RESTRICT,
    selected_date date NOT NULL,
    previous_rdo_id varchar(36),
    source_version bigint NOT NULL,
    payload_hash varchar(64) NOT NULL,
    coverage_json jsonb NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    stale_after timestamp with time zone NOT NULL,
    CONSTRAINT chk_rdo_context_receipt_positive CHECK (receipt_version > 0),
    CONSTRAINT chk_rdo_context_snapshot_hash CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT fk_rdo_context_previous_same_obra
        FOREIGN KEY (previous_rdo_id, obra_id)
        REFERENCES rdo(id, obra_id) ON DELETE RESTRICT
);

CREATE INDEX idx_rdo_context_snapshot_scope
    ON rdo_creation_context_snapshot (obra_id, selected_date, generated_at DESC);
