package com.projeto.cortex.config;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

class PostgresqlBaselineResourceContractTest {

    private static final Path POSTGRESQL_MIGRATIONS = Path.of(
            "src/main/resources/db/migration-postgresql"
    );
    private static final String BASELINE_FILENAME = "V44__postgresql_schema_baseline.sql";

    private static final List<Pattern> MYSQL_ONLY_SYNTAX = List.of(
            Pattern.compile("\\bENGINE\\s*=", Pattern.CASE_INSENSITIVE),
            Pattern.compile("\\bCHARACTER\\s+SET\\b", Pattern.CASE_INSENSITIVE),
            Pattern.compile("\\bCOLLATE\\b", Pattern.CASE_INSENSITIVE),
            Pattern.compile("\\bAUTO_INCREMENT\\b", Pattern.CASE_INSENSITIVE),
            Pattern.compile("\\bON\\s+DUPLICATE\\s+KEY\\b", Pattern.CASE_INSENSITIVE),
            Pattern.compile("\\bLAST_INSERT_ID\\b", Pattern.CASE_INSENSITIVE)
    );

    @Test
    void containsExactlyOnePostgresqlV44Baseline() throws IOException {
        assertThat(v44Migrations())
                .extracting(path -> path.getFileName().toString())
                .containsExactly(BASELINE_FILENAME);
    }

    @Test
    void baselineUsesPostgresqlDialectAndCentralizedTimestampTrigger() throws IOException {
        String sql = Files.readString(singleBaseline());
        String normalizedSql = sql.toLowerCase(Locale.ROOT);

        assertThat(MYSQL_ONLY_SYNTAX)
                .allSatisfy(pattern -> assertThat(pattern.matcher(sql).find())
                        .as("baseline must reject MySQL-only token %s", pattern.pattern())
                        .isFalse());
        assertThat(normalizedSql).doesNotContain("pdoc_snapshot");
        assertThat(normalizedSql).contains(
                "jsonb",
                "bytea",
                "generated",
                "on conflict",
                "create or replace function cortex_touch_atualizado_em()",
                "returns trigger"
        );
    }

    @Test
    void baselinePreservesCoreForeignKeyPathsAndEventOrdering() throws IOException {
        String sql = normalizedBaseline();

        assertThat(sql).contains(
                "create table asset_alias",
                "foreign key (asset_id) references asset(id)",
                "create table auth_identity",
                "foreign key (colaborador_id) references colaborador(id)",
                "create table programacao_operacional",
                "foreign key (obra_id) references obra(id)",
                "create table rdo",
                "foreign key (programacao_id) references programacao_operacional(id)",
                "foreign key (rdo_id) references rdo(id)",
                "create table pdor_snapshot",
                "create table obra_geometria"
        );

        String event = tableDefinition(sql, "cortex_evento_operacional");
        assertThat(event).contains(
                "sequencia bigint generated by default as identity primary key",
                "commit_seq bigint not null unique",
                "payload_json jsonb"
        );
        assertThat(sql).contains(
                "insert into cortex_evento_commit_sequence (id, ultima_commit_seq)",
                "values (1, 0)",
                "on conflict (id) do nothing",
                "foreign key (evento_servidor_commit_seq) references cortex_evento_operacional(commit_seq)"
        );
    }

    @Test
    void baselineUsesJsonbForOperationalPayloadsAndPostgresqlPartialIndexes() throws IOException {
        String sql = normalizedBaseline();

        assertJsonColumnsUseJsonb(sql, "cortex_objeto");
        assertJsonColumnsUseJsonb(sql, "cortex_evento_operacional");
        assertJsonColumnsUseJsonb(sql, "cortex_mapeamento_legado");
        assertJsonColumnsUseJsonb(sql, "cortex_evidencia_operacional");
        assertJsonColumnsUseJsonb(sql, "sync_mutacao_cliente");
        assertJsonColumnsUseJsonb(sql, "ontology_entities");
        assertJsonColumnsUseJsonb(sql, "ontology_relations");
        assertJsonColumnsUseJsonb(sql, "ontology_events");
        assertThat(tableDefinition(sql, "obra_geometria"))
                .contains("geometria_json jsonb not null", "propriedades_json jsonb not null");
        assertThat(sql).contains(
                "create unique index uq_cortex_relacao_ativa",
                "where ativa is true",
                "create unique index uq_operational_states_current",
                "where valid_to is null"
        );
    }

    @Test
    void baselineKeepsObjectsOutOfPostgresqlAndBinaryDataInsideWebauthnBoundary()
            throws IOException {
        String sql = normalizedBaseline();

        assertObjectStorageBoundary(sql, "importacao_rdo", "storage_key varchar(512)");
        assertObjectStorageBoundary(sql, "stavia_contexto_obra", "storage_key varchar(512)");
        assertObjectStorageBoundary(sql, "rdo_attachment", "storage_ref varchar(500)");

        String credential = tableDefinition(sql, "auth_webauthn_credential");
        assertThat(credential).contains(
                "credential_id bytea not null",
                "user_handle bytea not null",
                "public_key_cose bytea not null"
        );
    }

    @Test
    void baselineSeparatesEnglishAndPortugueseTimestampTriggers() throws IOException {
        String sql = normalizedBaseline();

        assertThat(sql).contains(
                "create or replace function cortex_touch_updated_at()",
                "new.updated_at = current_timestamp(6)",
                "create trigger trg_asset_touch_updated_at",
                "create trigger trg_ontology_entities_touch_updated_at",
                "create trigger trg_obra_touch_atualizado_em",
                "create trigger trg_sync_mutacao_cliente_touch_atualizado_em"
        );
    }

    private static void assertObjectStorageBoundary(String sql, String table, String storageColumn) {
        String definition = tableDefinition(sql, table);
        assertThat(definition).contains(storageColumn).doesNotContain("arquivo_bytes", " bytea");
    }

    private static void assertJsonColumnsUseJsonb(String sql, String table) {
        String definition = tableDefinition(sql, table);
        Pattern jsonColumn = Pattern.compile("\\b[a-z0-9_]+_json\\s+(json|jsonb)\\b");
        var matches = jsonColumn.matcher(definition).results().toList();

        assertThat(matches).as("%s must declare JSON payload columns", table).isNotEmpty();
        assertThat(matches)
                .allSatisfy(match -> assertThat(match.group(1)).isEqualTo("jsonb"));
    }

    private static String tableDefinition(String sql, String table) {
        Pattern tablePattern = Pattern.compile(
                "create table\\s+" + Pattern.quote(table) + "\\s*\\((.*?)\\);",
                Pattern.CASE_INSENSITIVE | Pattern.DOTALL
        );
        var match = tablePattern.matcher(sql);
        assertThat(match.find()).as("baseline table %s must exist", table).isTrue();
        return match.group(1);
    }

    private static String normalizedBaseline() throws IOException {
        return Files.readString(singleBaseline()).toLowerCase(Locale.ROOT)
                .replaceAll("\\s+", " ");
    }

    private static Path singleBaseline() throws IOException {
        assertThat(v44Migrations())
                .as("PostgreSQL must have one clean-start V44 baseline")
                .extracting(path -> path.getFileName().toString())
                .containsExactly(BASELINE_FILENAME);
        return POSTGRESQL_MIGRATIONS.resolve(BASELINE_FILENAME);
    }

    private static List<Path> v44Migrations() throws IOException {
        try (Stream<Path> files = Files.list(POSTGRESQL_MIGRATIONS)) {
            return files
                    .filter(Files::isRegularFile)
                    .filter(path -> path.getFileName().toString().startsWith("V44__"))
                    .sorted()
                    .toList();
        }
    }
}
